import Head from "next/head";
import { Inter } from "@next/font/google";
import { createClient } from "next-sanity";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ blogs }) {
  console.log(blogs);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Hello, My name is Mateen Nawaz</h1>
      </div>
    </>
  );
}

// code for connecting to sanity server
export async function getServerSideProps(context) {
  const client = createClient({
    projectId: "o7156ep0",
    dataset: "production",
    useCdn: true,
  });

  // GROQ code below. GROQ is simply use to run a sanity query
  const query = `*[_type == "blog" ]`;

  // Here fetch is a sanity fetch function
  const blogs = await client.fetch(query);

  // return a list of blogs
  return {
    props: {
      blogs,
    },
  };
}
